### PR TITLE
Create calendar list item class reposition

### PR DESCRIPTION
**Pull request by theronakpatel**

### CODE REVIEW

**Comment by theronakpatel** [comment]
@the-djmaze I made one mistake to place the function  `createCalendarListItem`  into correct place. it must be under `class NextcloudCalendarsPopupView` function. To correct this I created this MR. 

Please merge it urgently , and re-release  the version . :)

**Comment by theronakpatel** [comment]
@the-djmaze I deployed this MR in my local and it is how this works correctly. 

https://github.com/the-djmaze/snappymail/assets/11226784/a0621ac1-174f-4386-95f5-1fe31221fcef

**Comment by the-djmaze** [comment]
I will release when at PC

**Comment by theronakpatel** [comment]
@the-djmaze I am waiting for your release :) I want to update it in my system too at the earliest.

**Comment by theronakpatel** [comment]
@the-djmaze Can you update release or create new one ?

**Comment by the-djmaze** [comment]
Extension is released.

**Comment by Luncheon3462** [comment]
Thank you for quick turn around.   The Nextcloud version with the bug was 2.29.1.   Above you mention you released 2.25 with the fix.

I'm not a coder, but will Nextcloud know that 2.25 is more recent than 2.29.1?

**Pull request merged**
