### PR TITLE
Modern UI / Nextcloud Theme

### PR DESCRIPTION
**Pull request by hampoelz**
## Introduction

In order to improve the experience with snappymail - especially with the snappymail app for nextcloud - I decided to create a new snappymail theme that follows the style of nextcloud and offers an integration with the nextcloud theme app to provide a seamless experience.

Already mentioned in: #96 and #569 

### SnappyMail's default CSS variables for styling

I didn't use SnappyMail's variables for two reasons:
- I've played around with these CSS variables provided by snappymail for styling, but they seemed incomplete and inconsistent.
- Since Snappymail needed a complete theme overhaul anyway, I redesigned each element individually.

So it was cleaner for me not to use the snappymail variables.

### placeholder for blocked images

Currently there are some issues with blocking images/tracking in mail - it leads to wrong layouts or even distorted images - and it just doesn't look good in the end.

My suggestion would be instead of displaying broken/not loaded images, display styleable placeholders with a width and height - like many other webmail pages (Roundcube, Protonmail, ...) do. 

### standalone SnappyMail theme

It would also be possible to add this theme to the "standalone" Snappymail version - color changes of the theme are possible through the `variables.css`-file I added. When the theme is done, it should be possible to change every single color using this file/css variables - unlike SnappyMail's current CSS variables.

_(Disadvantage: These variables are then applied globally to the entire theme and are not as modular as those of snappymail, where each area (login, settings, ...) can be color-adjusted individually.)_

### Nextcloud backwards compatibility

I only tested the theme on Nextcloud 25, as this is the upstream version. Theoretically, the theme could also be provided for older versions.

---

## Checklist

To give an insight into the current status of the theme, here is a checklist:

- [x] side panel
- [x] buttons
- [x] checkboxes
- [x] input & selection fields
- [x] message list & view
- [x] message flags
- [x] dropdown menus
- [x] popups
- [x] file picker
- [x] loading- & login-screen
- [x] responsive design
- [x] scrollbars
- [x] settings pages
- _placeholder for blocked images?_
- _[something else I forgot or is incomplete?]_

> ℹ️ The theme is currently in test phase. Feedback is appreciated.

---

## Conclusion

The theme isn't quite finished yet, but it's already usable. This pull request is used to provide some information about the status of the theme and to track the progress.

To have a larger discussion on any of the above topics, consider creating a separate issue as it is beyond the scope of this PR.

### CODE REVIEW

**Comment by the-djmaze** [comment]
Great work hampoelz!
Instead of `/integrations/nextcloud/snappymail/app/themes/Nextcloud/styles.css`
Could you put it in something like  `/integrations/nextcloud/snappymail/app/themes/Nextcloud25/styles.css`

This way there's my simple CSS and your terrific advanced one.
Then you don't have to solve conflicts with my changes and we could easily put yours as default and provide the other as reference as well so that people can modify yours/mine.

**Comment by the-djmaze** [comment]
Sorry, it seems i accidentally released your WIP in the Nextcloud release while i was testing your work.

I've removed it so that next release won't have it.

**Comment by hampoelz** [comment]
Ah, no problem. Let's just say it's a short public test. ;)

Btw, you might want to take a look at Nextcloud app release automations to prevent such things.
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/release_automation.html

**Comment by Niveshkrishna** [comment]
Great work @hampoelz this new theme looks amazing. Wondering what is pending for it be released @the-djmaze

**Comment by hampoelz** [comment]
@Niveshkrishna There are many little things that are not finished yet. In the checklist above you can see what is still missing.

**Comment by jonmoesli** [comment]
The theme seems very promising, is there a roadmap for inclusion in snappymail?
Will be available also for the "standalone" version (without nextcloud)?

Thank you for this great work!

**Comment by hampoelz** [comment]
@jonmoesli There's no exact roadmap as I'm very busy in college at the moment. But I guess I'll have time to finish the theme in the next few months.

I'd also be willing to make the theme compatible with the standalone version of snappymail, if @the-djmaze agrees. A further idea would then be that the main colors of the theme can be changed directly in the user interface _(similar to the Nextcloud version in the Nextcloud settings)_. However, I'm currently unfamiliar with the snappymail codebase and don't know how much work that would be.

**Comment by botsarenthuman** [comment]
Great work!

**Comment by botsarenthuman** [comment]
I'd be interested in sponsoring a bounty to get this work complete. Is that something that could be arranged?

**Comment by hampoelz** [comment]
If you want to sponsor a bounty, I would be up for it, but you really don't have to. This month I don't have much time to work on this PR anyway, because I need to do some other things first before I graduate next month. After that I plan to finish this new theme.

**Comment by botsarenthuman** [comment]
OK sounds good. I've never sponsored someone before so don't know the best way. I do know that the icons are not evenly spaced above the mail list, besides the compose window not being styled.

**Comment by hampoelz** [comment]
I've never had anything to do with sponsoring either.

You're right, that's because the default snappymail theme groups those buttons and I've tried to keep that. So would you prefer more space between the button groups to make it clearer, or should I remove the extra space between the groups completely?

Popup windows are WIP. The compose window is still missing styles for file attachments, the mail address suggestions and button margins. _(Apart from some fine tuning)_ Did I forget something?

**Comment by hampoelz** [comment]
@botsarenthuman I tried your suggestion to evenly space buttons in toolbars, but honestly it didn't improve clarity (especially in the composition window), and I agree with you that the current style isn't optimal either. So I've "reworked" the toolbar a bit to highlight the groups more again, and I think it's a lot better now.

**current**
current

**evenly spaced**
evenly

**rework**
rework

**current _(compose window)_**
toolbar-old


**rework _(compose window)_**
toolbar-new

**Comment by the-djmaze** [comment]
I don't have a favourite color to use.
Personally i use black, but i've seen a bunch of other colors, so just using Nextcloud default is fine by me.

Great job you're doing!

P.S. v2.28 has special CSS for RTL languages, so check your theme in Persian or Arabic ;)

**Comment by hampoelz** [comment]
@cm-schl glad you like the theme.

The white on white text should be fixed now. 👍

Another thing I noticed on your screenshot is that the buttons are not rounded. Unfortunately, I can't reproduce that. They should look like this:
image

What browser are you using, and which version?

**Comment by hampoelz** [comment]
> I'm using Firefox 112.0 on Ubuntu (Mozilla Firefox Snap). I copied your files of this PR manually to my test install, maybe I made some error 🤔

Thank you! Apparently Firefox ≤ v112 doesn't support a css feature used in the theme for button groups. _(I probably missed that one)_ Also, firefox doesn't seem to have applied the fallback styles. Should be fixed now as well.

**Comment by cm-schl** [comment]
Hi @hampoelz ,

something now changed 👍 - but the group on the left side (on top of the list of mails) looks different like on the right side (on top of the opened mail) 😉 .
grafik

**Comment by hampoelz** [comment]
You are right, and this is something I am not really satisfied with. I decided to change the border radius of grouped buttons in the message list toolbar as a fallback, since a CSS feature for the "new" button group is not yet supported in Firefox ≤ v112.  Otherwise, the toolbar would look strange if some buttons are hidden, for example, in the Drafts or Archive folder:

image

If you want, I could use a larger border radius as a fallback for the message list toolbar, and maybe evenly space the buttons. See https://github.com/the-djmaze/snappymail/pull/629#issuecomment-1557616852

Anyway, in Firefox 113 everything will work ;)

**Comment by cm-schl** [comment]
Oh sorry, I've read that comment in the past but forgot it 😉.
I'm completely ok with this when in future versions of Firefox this is solved automatically, no need to do additional work that then will be deprecated 👍.

One thing i saw is that some menus are centered, others not:
grafik
grafik
grafik

Personally I would opt against a centered menu, but that's up to you 🙂

**Comment by hampoelz** [comment]
@cm-schl totally agree with you, I thought about it too but apparently forgot it. I've changed it now. 👍

**Comment by hampoelz** [comment]
@the-djmaze My main goal for this theme was/is to make it as detailed as possible - this resulted in several hundreds lines of CSS. So currently I don't have the capacity to do the same for the RTL layout. However, I'll fix styles that are completely broken.

Maybe I missed something, but wouldn't it be easiest to use something like `transform: scaleX(-1);`? That would prevent the pain in fixing styles in RTL layout, since theoretically all styles with horizontal properties would have to be changed.

**Comment by hampoelz** [comment]
The theme should be quite finished now. I use it daily and don't notice any problems anymore.

A quick summary of what this pull request is all about:
- elements follow the style of Nextcloud 25 and newer
- some elements are completely reworked (button groups, nextcloud file attach button, ...)
- mobile layout has been improved (larger controls, responsive admin panel, horizontal contacts popup layout on small screens, better dropdown positioning on small screens, ...)
- Nextcloud styles/themes are passed through when snappymail is used in an iframe
- a light/dark mode that follows the system preferences, as long as no particular mode is specified

@the-djmaze As long as Snappymail is my daily driver and I've the time, I'm willing to keep updating this theme, fix issues and style newly added features. So if there are any changes or anything I need to add/update, let me know. Feel free to assign issues regarding this theme to me.

If you want, we could also transfer some of the mobile layout enhancements to the global style sheets.

After the merge of this pr, I'll create a separate pull request for further fixes.

**Comment by elhananjair** [comment]
@hampoelz How can we install this theme for a test?

**Comment by hampoelz** [comment]
@elhananjair You need to perform the following steps to install the theme:

First download the files [`styles.css`](https://raw.githubusercontent.com/hampoelz/PR_SnappyMail/nc-theme/snappymail/v/0.0.0/themes/NextcloudV25%2B/styles.css) and [`images/preview.png`](https://raw.githubusercontent.com/hampoelz/PR_SnappyMail/nc-theme/snappymail/v/0.0.0/themes/NextcloudV25%2B/images/preview.png) from this pull request.

Then create a folder named "NextcloudV25+" inside `your_nextcloud_root/custom_apps/snappymail/app/themes/` if you're using Nextcloud, or `your_snappymail_root/snappymail/v/x.x.x/themes/` if you're using the standalone SnappyMail version.

Finally, copy the previously downloaded files to `.../NextcloudV25+/styles.css` and `.../NextcloudV25+/images/preview.png`.

Since the theme isn't officially included yet, you need to reinstall it after each SnappyMail update.

_Note: Depending on your Nextcloud installation, SnappyMail may be installed in the `apps` folder instead of `custom_apps`._

**Comment by elhananjair** [comment]
Thank you very much, I like it a lot and it seems complete, here are some little comments I have on it on my first use:

**Text-overflow** 
image

**HTML Rendered differently**
image

**New tags do not have color assigned**
image

**Comment by hampoelz** [comment]
@elhananjair Thank you very much for your report.

- The text overflow issue in the sidebar menu items should be fixed now.
- The issue with the HTML rendering shouldn't be related to the theme.
- I didn't set a color for custom tags, since they don't actually have one. But you're right, this isn't optimal. The custom tags in the dropdown are now marked with the same gray color as in the list of assigned message tags.

**Comment by elhananjair** [comment]
Hello @hampoelz 
I wanted to suggest this change if you could add more contrast to the layout, I tried this take a look and comment...
1. Search input should not have a check box I guess
2. The top tools are not well contrasted with the component listing emails and the content on the right (In my opinion). This will help us to focus on a new email list and easily apply the top options. 

image

**Comment by hampoelz** [comment]
Hey @elhananjair,

The checkbox next to the search bar is for selecting all mails at once and is provided by SnappyMail, not by the theme.

I don't want to change the contrast much as it wouldn't match the rest of the Nextcloud theming. Also, I don't think it's a good idea to separate the search more from the list. However, after some fiddling around, I came up with the following style, which would at least contrast the top tools slightly:

Screenshot from 2023-08-03 20-51-01

**Comment by elhananjair** [comment]
Hello @hampoelz 

I liked the style you applied to the top tools, which, I think is enough for slight contrast between the top tools and other components.

**Comment by cm-schl** [comment]
@the-djmaze the work of @hampoelz looks very good, would you add something or could this PR be merged? 🙂

**Comment by johnnyq** [comment]
Yup I think its ready for the merge as well

**Comment by elhananjair** [comment]
I hope this theme will be the default theme for Snappymail.

**Comment by cm-schl** [comment]
Thanks again @hampoelz for your great work 🙂🥳

**Comment by eibex** [comment]
Is it possible to use this without the Nextcloud app? I run snappymail on a separate domain but it can also be accessed via an iframe on nextcloud

**Comment by hampoelz** [comment]
The theme is not dependent on Nextcloud. So it would be theoretically possible.

_It even contains styles for some elements that are not shown in the Nextcloud version of SnappyMail, like the login screen._

**Comment by the-djmaze** [comment]
> The theme is not dependent on Nextcloud. So it would be theoretically possible.

Then i will move it from https://github.com/the-djmaze/snappymail/tree/master/integrations/nextcloud/snappymail/app/themes/NextcloudV25%2B to https://github.com/the-djmaze/snappymail/tree/master/snappymail/v/0.0.0/themes

**Comment by hampoelz** [comment]
I will take this into consideration @jdaviescoates. But this may take a few weeks as I want to wait for feedback / issues before creating a PR with fixes and improvements for the theme.

**Pull request merged**
