### PR TITLE
Keep open `attachments` section

### PR DESCRIPTION
**Pull request by theronakpatel**

### CODE REVIEW

**Comment by the-djmaze** [comment]
Why?
If i closed it, maybe i want to keep it closed until i open it again?

**Comment by the-djmaze** [comment]
You could write a plugin for what you want.
Some JavaScript to modify MailMessageView will be sufficient.
```js
dom.querySelector('.attachmentsControls').dataset.bind = '';
const ds = dom.querySelector('.attachmentsPlace').dataset;
ds.bind = ds.bind.replace('showAttachmentControls', 'true');
```

For more info investigate https://github.com/the-djmaze/snappymail/tree/master/plugins/example

**Comment by akhil1508** [comment]
@the-djmaze 

For me, it makes sense to allow admins to set sensible defaults for this option. I would like to have them always open (like in Gmail or Outlook) for my users.

Could it be a config option instead? Something like `always_expand_attachments` with options `on` and `off` where `off` will follow the user preference.

**Comment by the-djmaze** [comment]
What about "allow users to show/hide attachment controls" ?

**Comment by akhil1508** [comment]
> What about "allow users to show/hide attachment controls"?

@the-djmaze Thanks a lot for the plugin code. Will try to modify it as a setting soon.

**Pull request closed without merging**
