### PR TITLE
Update lessphp library

### PR DESCRIPTION
**Pull request by Alphix**

### CODE REVIEW

**Comment by the-djmaze** [comment]
This will break the autoloader.
File was named lessc.php on purpose for the inbuild spl autoloader.
lessc.inc.php will not load and therefore themes are broken.

Also i had issues with 0.5 to get it properly working.

Did you test the changes?

**Comment by Alphix** [comment]
> This will break the autoloader.
> File was named lessc.php on purpose for the inbuild spl autoloader.
> lessc.inc.php will not load and therefore themes are broken.
> 
> Also i had issues with 0.5 to get it properly working.
> 
> Did you test the changes?

Haha....yes, I did...and I just realised that I did so by running `relelase.php` and then untarring the resulting tarball over the existing installation. Which usually works well. Except, of course, when I've renamed a file *doh*.

> P.S. Now that i think about it. Maybe just drop the whole lessc and just use plain css.
> Lessc hasn't been updated in 3 years and the wikimedia version is too big for the simple purpose snappymail uses it.

I considered that option as well. I'll have a look and see how much work it'd be to convert the existing themes to plain CSS.

**Comment by the-djmaze** [comment]
See mentioned commit.
It was not hard, most important was a regular expression for theme images in ` snappymail/v/0.0.0/app/libraries/RainLoop/Actions/Themes.php`

**Comment by the-djmaze** [comment]
I am closing this PR due to the changes to .css files.
It is now deprecated to use .less files.

**Pull request closed without merging**
