### PR TITLE
Upgraded and improved editor features

### PR DESCRIPTION
**Pull request by rezaei92**
Hello,
It seems that due to issues and the absence of certain features in the editor, which have been frequently mentioned in various issues, it would be better to make changes and developments in this section and upgrade the Squire editor version along with it. Some of the issues include the lack of text alignment, problems with text direction, the inability to add text styles as inline CSS, issues with directly copying tables, and visual and display problems.

Therefore, implementing these changes will address many needs, especially for RTL languages. I would appreciate it if you could accept this PR to improve performance and provide more convenience for users.

image

### CODE REVIEW

**Comment by phsc84** [comment]
Great work, would love to give it a try!
Just a sidenote: [Squire 2.3.2](https://github.com/fastmail/Squire/commit/cbd8881e78c2af0305a0b6a06cdff16c0c0b05ed) is already out.

**Comment by rezaei92** [comment]
> Great work, would love to give it a try! Just a sidenote: [Squire 2.3.2](https://github.com/fastmail/Squire/commit/cbd8881e78c2af0305a0b6a06cdff16c0c0b05ed) is already out.

Thanks for your feedback. I've done.

**Comment by the-djmaze** [comment]
Yes, it would be nice if Squire-RTE can be used.

But i also see you added DOMPurify.
Can you remove DOMPurify?

**Comment by rezaei92** [comment]
Thank you so much.
I removed it.

**Comment by the-djmaze** [comment]
Ok, Squire-RTE can't be used by default due to the important changes.
If you are missing something, see https://github.com/the-djmaze/Squire

Feel free to create a new PR with only the RTL fixes.

**Pull request closed without merging**
