### PR TITLE
Add Docker release image and improve development experience

### PR DESCRIPTION
**Pull request by FWest98**
Added a docker production-ready image based on https://gitlab.com/youtous/rainloop. Also updated and improved the docker development environment for easier use. This includes the introduction of `.env` file support for customizing the ports the dev app is running on.

The docker build of the release image is now part of the release script, with a question to the user whether or not to execute it.

### CODE REVIEW

**Review by the-djmaze — CHANGES_REQUESTED** [review]
The following line breaks the release. Could you revert the change?

`$tar->buildFromDirectory('./snappymail/', "@v/{$package->version}@");`

**Comment by the-djmaze** [comment]
I've made the change myself.
Use as `release.php --docker`

**Comment by FWest98** [comment]
Ah I was just about to reply. Thanks for merging! In my experience, the old version broke the build when you had a development build running since it was iterating over files in /data that were not always accessible, even though they would not have been included anyway because of the filter.

What exactly broke with the new line I added? Did the archive directory structure change? Then it might be easiest to adapt the Dockerfile to use a different directory rather than adapting the release script.

**Comment by the-djmaze** [comment]
> What exactly broke with the new line I added? Did the archive directory structure change?

Yes the directory structure changed. 'snappymail' was missing and it started with 'v'.
That's why i made it a command option.

I've also bumped docker to use 7.4-fpm and removed the obsolete mcrypt and added the missing xxtea

**Comment by FWest98** [comment]
Ah ok, I thought I checked it. In that case I would propose to remove the if check from the release script and it should still work (based on https://gitlab.com/youtous/rainloop/-/blob/master/Dockerfile where they download a zip file with the same structure as the desired zip from snappymail).

I think it would also be good to replace the user query on line 123 of release.php with the value of the new docker parameter, to ease future automation of this process.

**Pull request merged**
