### PR TITLE
draft: add lang

### PR DESCRIPTION
**Pull request by avinash-0007**
Allow nextcloud language to work with snappy

### CODE REVIEW

**Comment by the-djmaze** [comment]
Please check release v2.31 with the new extension.
It should solve most languages.

Then see if your changes are still needed on some way.

**Comment by avinash-0007** [comment]
> Please check release v2.31 with the new extension. It should solve most languages.
> 
> Then see if your changes are still needed on some way.
> 
> Probably here now:
> 
> https://github.com/the-djmaze/snappymail/blob/ddc953f4fad60bded880275b4ad25143f01203d4/plugins/nextcloud/index.php#L248-L257

@the-djmaze in the above code , i see that we are still using getLocaleCode so it will work with getLocaleCode but we want it to work with user language as in nextcloud when user change language then page language get changed.WDYT?

**Comment by the-djmaze** [comment]
When i went to user settings and change language.
Then go back to SnappyMail. The language is changed.

Does it not work for you?

**Comment by avinash-0007** [comment]
@

> When i went to user settings and change language. Then go back to SnappyMail. The language is changed.
> 
> Does it not work for you?

No. I updated it to v2.31 and its not working. I change the language and i dont see snappy language change with this.

**Comment by the-djmaze** [comment]
I've noticed there was bug. Fixed that

**Comment by avinash-0007** [comment]
> I've noticed there was bug. Fixed that

@the-djmaze so are you releasing new version with this bug fix?

**Comment by the-djmaze** [comment]
Already done. Nextcloud -> Admin -> Additional Settings -> SnappyMail Admin -> Extensions

**Comment by avinash-0007** [comment]
> Already done. Nextcloud -> Admin -> Additional Settings -> SnappyMail Admin -> Extensions

@the-djmaze with this change i still see you are getting Locale Code:$sLanguage = \strtr(\OC::$server->getL10N('core')->getLocaleCode(), '_', '-');

But in nextcloud when we change language then actually page language get change not on locale change so we need to change snappy mail language when language get changed not when locale gets change.

**Pull request closed without merging**
