### PR TITLE
Enhancement (docker): Add more archs

### PR DESCRIPTION
**Pull request by leojonathanoh**
The build succeeded, see https://github.com/leojonathanoh/snappymail/pull/2.

```sh
docker pull ghcr.io/leojonathanoh/snappymail:pr-2-0d9c2a8
docker pull leojonathanoh/snappymail:pr-2-0d9c2a8
```

### CODE REVIEW

**Comment by the-djmaze** [comment]
Should we really add ARMv6 and ARMv7?
Besides that hey are old... They are 32bit and that can have conflicts, because IMAP uses 64bit numbers (don't work in PHP 32bit).

**Comment by leojonathanoh** [comment]
Agreed. They are taking super long to build, over an hour. So, only `arm64`?

**Comment by leojonathanoh** [comment]
worth adding `linux/s390x`?

**Comment by the-djmaze** [comment]
> worth adding `linux/s390x`?

When people start using 64bit mainframes and docker. They will also probably ask to support MAILBOX-REFERRALS (RFC 2193, 5258) :laughing: 
As:
```
A001 DELETE "SHARED/FOO"
A001 NO [REFERRAL IMAP://user;AUTH=*@SERVER2/SHARED/FOO] Remote mailbox. Try SERVER2.
```

**Comment by leojonathanoh** [comment]
don't really know what that means 😕 you mean that's only supported on `390x`?

**Comment by the-djmaze** [comment]
> don't really know what that means 😕

IMAP can be setup to have "remote" mailboxes.
Say your enterprise server/mainframe is full/overloaded and you moved half of the mailboxes to a different server.
Then IMAP can tell the client (SnappyMail) that some are `\Remote` and then we need RLIST or RLSUB commands to list them or the LIST-EXTENDED `REMOTE`.

With `390x` i think we are more in the boat to implement this IMAP feature then with normal docker instances.

**Comment by leojonathanoh** [comment]
i see, shouldn't this be a IMAP protocol specific implementation? for it to be specific to an arch is strange.

**Comment by the-djmaze** [comment]
It is IMAP protocol specific. But i wonder if we should support 390x

**Comment by leojonathanoh** [comment]
yeah. but so long as the builds / tests succeed, it is assumed that 390x should work just as any arch would. It's not very used much in the wild anyway 🥲

**Comment by leojonathanoh** [comment]
guess we could drop it? your take i guess 😄

**Comment by the-djmaze** [comment]
> It's not very used much in the wild anyway 🥲

Then skip it. Arm64 will be enough then.
Pretty useless to wait longer for archs that are hardly used.

**Comment by the-djmaze** [comment]
I will keep in mind to drop `linux/386` within a few years as well.

https://github.com/the-djmaze/snappymail/issues/830

**Comment by the-djmaze** [comment]
```
Error: Input does not meet YAML 1.2 "Core Schema" specification: push
Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

**Comment by leojonathanoh** [comment]
Let me rebase

**Comment by leojonathanoh** [comment]
where are you seeing the yaml error?

**Comment by the-djmaze** [comment]
at docker build

**Comment by leojonathanoh** [comment]
see it, second

**Comment by leojonathanoh** [comment]
39 mins for cacheless builds, guess that's fine? but there's docker caching in the CI, so if it hits the cache, it will be much faster. Which, should be most of the time.

**Pull request merged**
