### PR TITLE
Fix issues with SMTP login mechanisms except "LOGIN"

### PR DESCRIPTION
**Pull request by akhil1508**
Please check comment [here](https://github.com/the-djmaze/snappymail/pull/423#issuecomment-1350739102)

### CODE REVIEW

**Comment by the-djmaze** [comment]
Instead of revert, we could also disable SASLMechanisms.
Next release will already have more advanced per Domain setup to set certain IMAP settings there instead of global.

https://github.com/the-djmaze/snappymail/issues/724#issuecomment-1348881897

**Comment by akhil1508** [comment]
@the-djmaze Does this mean the plan is to drop OAUTHBEARER/XOAUTH2 support entirely?

**Comment by the-djmaze** [comment]
I mean, disable PLAIN for #423 and/or disable others as there are more broken IMAP servers between the issues.
As they are external issues, disabling broken SASL mechanisms should solve it.

Then this revert also makes sense without pthers needing plugins to disable mechanisms

**Comment by the-djmaze** [comment]
Made the change.
As of next release people with issue #693 and #423 can manually modify `data/_data_/_default_/domains/domain.tld.json`

```json
{
    "name": "domain.tld",
    "IMAP": {
        "host": "localhost",
        "port": 143,
        "type": 2,
        "timeout": 300,
        "shortLogin": false,
        "sasl": [
            "SCRAM-SHA3-512",
            "SCRAM-SHA-512",
            "SCRAM-SHA-256",
            "SCRAM-SHA-1",
            "PLAIN",
            "LOGIN"
        ],
        "ssl": {
            "verify_peer": true,
            "verify_peer_name": true,
            "allow_self_signed": false,
            "SNI_enabled": true,
            "disable_compression": true,
            "security_level": 1
        },
        "disable_list_status": false,
        "disable_metadata": false,
        "disable_move": false,
        "disable_sort": false,
        "disable_thread": false,
        "use_expunge_all_on_delete": false,
        "fast_simple_search": true,
        "force_select": false,
        "message_all_headers": false,
        "message_list_limit": 0,
        "search_filter": ""
    }
}
```
And also the "sasl" for SMTP and Sieve

**Pull request merged**
